version: '3'
services:
  app:
    image: ${IMAGE_NAME:-j0occ0c44s40og4owgskwk04:latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    command: npm run serve
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3